openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://api.keypeer.org
info:
  description: Proposed API
  version: "1.0.0"
  title: Keypeer Api
  contact:
    email: admin@keypeer.org
  license:
    name: Unknown
    url: ''
tags:
  - name: admins
    description: Secured Admin-only calls
  - name: consumers
    description: Operations available to regular users
paths:
  /keys/api/1.0.0/provider:
    get:
      tags:
        - consumers
      summary: Provider ID list
      description: Returns a list of providers
      responses:
        '200':
          description: Returns a list of providers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/provider_'
        '400':
          description: bad input parameter
  /keys/api/1.0.0/provider/{provider_id}:
    get:
      tags:
        - consumers
        - admins
      summary: Service API KEY
      description: |
        Returns the provider service api key for {provider_id} 
      parameters:
        - in: path
          name: provider_id
          description: Internal ID for available services
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Return service api key
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/provider_providerID'
        '400':
          description: bad input parameter
  /keys/api/1.0.0/consumer/{consumer_id}:
    get:
      tags:
        - consumers
      summary: Request user data
      description: |
        Returns a dict containing varoius user data
      parameters:
        - in: path
          name: consumer_id
          description: End User ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Return User Data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/consumer_consumerData'
        '400':
          description: bad input parameter
  /keys/api/1.0.0/consumer:
    get:
      tags:
        - consumers
      summary: Request user data
      description: |
        Returns a dict userids
      responses:
        '200':
          description: Return Userids
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/consumer_'
        '400':
          description: bad input parameter
  /keys/api/1.0.0/consumer/{consumer_id}/application/{application_id}:
    get:
      tags:
        - consumers
      summary: Retrieve Service Api keys for users application, application_id
      description: |
        Returns service api key
      parameters:
        - in: path
          name: consumer_id
          description: Consumer ID
          required: true
          schema:
            type: string
        - in: path
          name: application_id
          description: Consumer Application ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Returns service api keys for Application and user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/consumer_providerID'
        '400':
          description: bad input parameter
    post:
      tags:
        - consumers
      summary: Add consumer application
      description: |
        Returns true if consumer application is added
      parameters:
        - in: path
          name: consumer_id
          description: consumer_id
          required: true
          schema:
            type: string
        - in: path
          name: application_id
          description: Consumer Application ID
          required: true
          schema:
            type: string
      requestBody:
        description: Request to add consumer application 
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/consumer_consumerAddAppplication'
      responses:
        '201':
          description: success
    delete:
      tags:
        - consumers
      summary: remove consumer application
      description: |
        Returns true if consumer application is updated
      parameters:
        - in: path
          name: consumer_id
          description: Consumer ID
          required: true
          schema:
            type: string
        - in: path
          name: application_id
          description: Consumer Application ID
          required: true
          schema:
            type: string
      responses:
        '201':
          description: delete success
  /keys/api/1.0.0/application:
    get:
      tags:
        - consumers
        - admins
      summary: Return array of applications
      description: |
         Obtain list of application providers
      responses:
        '200':
          description: Returns service api key
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/application_applicationID'
        '400':
          description: bad input parameter
    post:
      tags:
        - admins
      summary: Add application application
      description: |
        Returns true if consumer application is added
      requestBody:
        description: Request to add consumer application 
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/application_applicationID'
      responses:
        '201':
          description: success
  /keys/api/1.0.0/application/{application_id}:
    get:
      tags:
        - consumers
        - admins
      summary: Return array of providers for an application
      description: |
         Obtain list of application providers
      parameters:
        - in: path
          name: application_id
          description: Consumer Application ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Returns service api key
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/application_applicationID'
        '400':
          description: bad input parameter
  /keys/api/1.0.0/application/{application_id}/provider:
    get:
      tags:
        - consumers
      summary: Return array of application providers
      description: |
         Obtain application provider keys
      parameters:
        - in: path
          name: application_id
          description: Consumer Application ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Return array of application provider keys
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/application_applicationID_providerID'
        '400':
          description: bad input parameter
  /keys/api/1.0.0/application/{application_id}/provider/{provider_id}:
    get:
      tags:
        - consumers
      summary: Return provider keys for application & provider
      description: |
         Obtain application provider keys
      parameters:
        - in: path
          name: application_id
          description: Consumer Application ID
          required: true
          schema:
            type: string
        - in: path
          name: provider_id
          description: Internal ID for available services
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Return array of application provider keys
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/application_applicationID_providerID'
        '400':
          description: bad input parameter
components:
  schemas:
    provider_:
      type: array
      items:
        type: object
        properties:
          provider_id:
            type: string
            format: uuid
          name:
            type: string
        example:
        - provider_id: d290f1ee-6c54-4b01-90e6-d701748f0851
          name: Mapbox
        - provider_id: d290f1ee-6c54-4b01-90e6-78987hj23678
          name: Here
    consumer_:
      type: array
      items:
        type: object
        properties:
          consumer_id:
            type: string
            format: uuid
        example:
        - consumer_id: d290f1ff-6c54-4b01-90e6-d701748f0851
        - consumer_id: d290f1ff-6c54-4b01-90e6-78987hj23678
    provider_providerID:
      type: object
      required:
        - provider_id
        - keypeer_api_key
        - token
      properties:
        provider_id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        keypeer_api_key:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-j78b390f0367
        token:
          type: string
          format: base64
          example: dG9rZW4gZXhhbXBsZSBpbiBiYXNlNjQ=
    consumer_consumerData:
      type: array
      items:
        type: object
        properties:
          application_id:
            type: string
            format: uuid
          provider_id:
            type: string
            format: uuid
          expiry:
            type: string
            description: ISO 8601 Format
        example:
        - application_id: d290f1ee-6c54-4b01-90e6-hjsd6777h389
          provider_id: d290f1ee-6c54-4b01-90e6-78987hj23678
          expiry: 2023-03-25T16:33:23Z
        - application_id: d290f1ee-6c54-4b01-90e6-hjsd6777h389
          provider_id: d290f1ee-6c54-4b01-90e6-78987hj23678
          expiry: 2023-03-25T16:33:23Z
    consumer_consumerAddAppplication:
      type: object
      properties:
        consumer_id:
          type: string
          format: uuid
        keypeer_api_key:
          type: string
          format: uuid
        application_id:
          type: string
          format: uuid
        expiry:
          type: string
          description: ISO 8601 Format
      example:
      #Ask poetaster: Should we remove {application_id} from path since it's in request body?
      - consumer_id: d290f1ee-6c54-4b01-90e6-hjsd6777h389
        keypeer_api_key: d290f1ee-6c54-4b01-90e6-78987hj23678
        application_id: d290f1ee-6c54-4b01-90e6-78987hj23678
        expiry: 2023-03-25T16:33:23Z
    consumer_consumerUpdateAppplication:
        type: object
        properties:
          consumer_id:
            type: string
            format: uuid
          keypeer_api_key:
            type: string
            format: uuid
          application_id:
            type: string
            format: uuid
          expiry:
            type: string
            description: ISO 8601 Format
        example:
        #Ask poetaster: Should we remove {application_id} from path since it's in request body?
        - consumer_id: d290f1ee-6c54-4b01-90e6-hjsd6777h389
          keypeer_api_key: d290f1ee-6c54-4b01-90e6-78987hj23678
          application_id: d290f1ee-6c54-4b01-90e6-78987hj23678
          expiry: 2023-03-25T16:33:23Z
    consumer_providerID:
      type: array
      items:
          type: object
          properties:
            provider_id:
              type: string
              format: uuid
            service_api_key:
              type: string
              format: uuid
          example:
          - provider_id: d290f1ee-6c54-4b01-90e6-78987hj23678
            service_api_key: d290f1ee-6c54-4b01-90e6-78987hj23678
          - provider_id: d290f1ee-6c54-4b01-90e6-78987hj23678
            service_api_key: d290f1ee-6c54-4b01-90e6-78987hj23678
    application_applicationID:
      type: array
      items:
          type: object
          properties:
            keypeer_api_key:
              type: string
              format: uuid
            application_id:
              type: string
              format: uuid
          example:
          - keypeer_api_key: d290f1ee-6c54-4b01-90e6-78987hj23678
            application_id: d290f1ee-6c54-4b01-90e6-78987hj23678
          - keypeer_api_key: d290f1ee-6c54-4b01-90e6-78987hj23678
            application_id: d290f1ee-6c54-4b01-90e6-78987hj23678
    application_applicationID_providerID:
      type: array
      items:
          type: object
          properties:
            service_api_key:
              type: string
              format: uuid
            expiry:
              type: string
              description: ISO 8601 Format
          example:
          - service_api_key: d290f1ee-6c54-4b01-90e6-78987hj23678
            expiry: 2023-03-25T16:33:23Z
          - service_api_key: d290f1ee-6c54-4b01-90e6-78987hj23678
            expiry: 2023-03-25T16:33:23Z
      
