name: Build and Deploy
on:
  push:
    tags:
      - "*"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: poetaster/github-pages-blog-action@v0.0.13
        with:
          branch: gh-pages # Optional branch for GitHub Pages
